# write_poem:
#   description: >
#     Write a poem about how CrewAI is awesome.
#     Ensure the poem is engaging and adheres to the specified sentence count of {sentence_count}.
#   expected_output: >
#     A beautifully crafted poem about CrewAI, with exactly {sentence_count} sentences.
#   agent: poem_writer

review_poem:
  description: >
    Review the poem for improvements in tone, rhythm, and clarity.
    Provide constructive feedback and suggest revisions to make the poem better.
  expected_output: >
    Suggestions to improve the poem, focusing on tone, rhythm, and clarity.
  agent: poem_editor
